### ISSUE TITLE
Target created layer

### ISSUE THREAD

**Issue by jeremieb** [NocheVolta/Framer-VerticalPanel#2]
Hey guys!

This module is great, but I've an issue to target the layer created. Am I missing something?

```
## PANEL
myPanel = new VerticalPanel
	initState: 'bottom'
	backgroundColor: '#444444'
	bottom: 19
	name: 'pan'

## PANEL - Elements
panSearchField.parent = pan
```
'pan' is not created and can't be the parent of panSearchField...

**Comment by NocheVolta** [comment]
Hi, you can use two methods to get those layers.

`myPanel.content` returns the visible layer (white as default)
`myPanel.wrapper` returns all the module layer. 

I'm not quite sure what are you trying to do with that example code, could please be more specific, thanks.

**Comment by jeremieb** [comment]
Yes, it worked with the .content. Thanks ;-)
